### ISSUE TITLE
Document GitHub action option PROJECT_PATH

### ISSUE THREAD

**Issue by peterpeterparker** [junobuild/docs#334]
# Motivation

In the [GitHub Actions](https://juno.build/docs/guides/github-actions) documentation we should document the option `PROJECT_PATH` which is handy when the deployment occurs in a sub-folder of the repo.

Example:

```
      - name: Deploy to Juno
        uses: junobuild/juno-action@main
        with:
          args: deploy
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
          PROJECT_PATH: demo/src/relying_party_frontend
```

# What to do

Document the option in a new or existing chapter of the documentation.
